config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  get "/auth/auth0/callback" => "auth0#callback"
  get "/auth/failure" => "auth0#failure"
  get "/auth/logout" => "auth0#logout"

  get "login", to: "login#index"

  resources :tasks, only: [:create, :update]
  resources :in_backlog_tasks, only: [:create, :update, :destroy]
  resources :events, only: [:create, :update, :destroy]
  resources :repeats, only: [:create, :update, :destroy]
  resource :configurations, only: [:show, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user

  validates :title, :datetime, presence: true

  scope :not_done, -> { where(done_at: nil) }
end

app/models/repeat.rb
class Repeat < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  enum status: [:pending, :completed, :cancelled, :in_backlog]

  validates :title, presence: true

  scope :ended_today, -> { where(ended_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day) }
  scope :pending_or_ended_today, -> { pending.or(ended_today) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :repeats, dependent: :destroy

  validates :auth0_id, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ActionView::RecordIdentifier
end

app/controllers/auth0_controller.rb
class Auth0Controller < ApplicationController
  def callback
    auth_info = request.env["omniauth.auth"]
    session[:userinfo] = auth_info["extra"]["raw_info"]

    auth0_id = session[:userinfo]["sub"].split("|")[1]
    User.find_or_create_by(auth0_id: auth0_id)

    redirect_to "/"
  end

  def failure
    @error_msg = request.params["message"]
  end

  def logout
    reset_session
    redirect_to logout_url
  end

  private

  def logout_url
    request_params = ActionController::Parameters.new({
      returnTo: root_url,
      client_id: ENV["AUTH0_CLIENT_ID"]
    }).permit(:returnTo, :client_id)

    URI::HTTPS.build(host: ENV["AUTH0_DOMAIN"], path: "/v2/logout", query: request_params.to_query).to_s
  end
end

app/controllers/authenticated_controller.rb
class AuthenticatedController < ApplicationController
  before_action :logged_in_using_omniauth?
  around_action :set_time_zone

  private

  def logged_in_using_omniauth?
    redirect_to login_path unless session[:userinfo].present?
  end

  def current_user
    User.find_by(auth0_id: auth0_id)
  end

  def auth0_id
    session[:userinfo]["sub"].split("|")[1]
  end

  def set_time_zone
    Time.use_zone(current_user.timezone || "UTC") { yield }
  end
end

app/controllers/configurations_controller.rb
class ConfigurationsController < AuthenticatedController
  def show
    @user = current_user
  end

  def update
    timezone = ActiveSupport::TimeZone[timezone_param]
    if timezone
      current_user.update(timezone: timezone.name)
    end

    render :index
  end

  private

  def timezone_param
    params.require(:user).permit(:timezone)[:timezone]
  end
end

app/controllers/events_controller.rb
class EventsController < AuthenticatedController
  def create
    event = Event.new(event_params)
    event.user = current_user
    event.save

    render turbo_stream: [
      turbo_stream.replace(
        :event_form,
        partial: "events/form",
        locals: {event: Event.new}
      ),
      turbo_stream.append(:events, partial: "events/event", locals: {event: event})
    ]
  end

  def update
    event = current_user.events.find(params[:id])
    event.update(done_at: Time.zone.now)

    render turbo_stream: turbo_stream.remove(dom_id(event))
  end

  def destroy
    event = current_user.events.find(params[:id])
    event.destroy

    render turbo_stream: turbo_stream.remove(dom_id(event))
  end

  private

  def event_params
    params.require(:event).permit(:title, :datetime)
  end
end

app/controllers/home_controller.rb
class HomeController < AuthenticatedController
  def index
    @tasks = current_user.tasks.pending_or_ended_today
    @backlog_tasks = current_user.tasks.in_backlog
    @events = current_user.events.not_done.order(datetime: :asc)
    @today_repeats = current_user.repeats.where("days @> ARRAY[?]::integer[]", [Time.zone.today.wday])
    @other_repeats = current_user.repeats.where.not("days @> ARRAY[?]::integer[]", [Time.zone.today.wday])

    @task = Task.new
    @backlog_task = Task.new
    @event = Event.new
    @repeat = Repeat.new
  end
end

app/controllers/in_backlog_tasks_controller.rb
class InBacklogTasksController < AuthenticatedController
  def create
    task = Task.new(task_params)
    task.status = :in_backlog
    task.user = current_user
    task.save

    render turbo_stream: [
      turbo_stream.replace(
        :in_backlog_task_form,
        partial: "tasks/in_backlog_form",
        locals: {task: Task.new}
      ),
      turbo_stream.append(:in_backlog_tasks, partial: "tasks/task", locals: {task: task})
    ]
  end

  def update
    task = current_user.tasks.find(params[:id])
    task.update(status: :pending)

    render turbo_stream: [
      turbo_stream.remove(dom_id(task)),
      turbo_stream.append(:tasks, partial: "tasks/task", locals: {task: task})
    ]
  end

  def destroy
    task = current_user.tasks.find(params[:id])
    task.destroy

    render turbo_stream: turbo_stream.remove(dom_id(task))
  end

  private

  def task_params
    params.require(:task).permit(:title)
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
  end
end

app/controllers/repeats_controller.rb
class RepeatsController < AuthenticatedController
  def create
    repeat = Repeat.new(repeat_params)
    repeat.user = current_user
    repeat.save

    render turbo_stream: [
      turbo_stream.replace(
        :repeat_form,
        partial: "repeats/form",
        locals: {repeat: Repeat.new}
      ),
      turbo_stream.append(:repeats, partial: "repeats/repeat", locals: {repeat: repeat})
    ]
  end

  def update
    repeat = current_user.repeats.find(params[:id])
    if params[:hit] == "done"
      repeat.update(hits: repeat.hits + [Date.today])
    elsif params[:hit] == "undo"
      repeat.update(hits: repeat.hits - [Date.today])
    end

    render turbo_stream: turbo_stream.replace(
      dom_id(repeat),
      partial: "repeats/repeat",
      locals: {repeat: repeat}
    )
  end

  def destroy
    repeat = current_user.repeats.find(params[:id])
    repeat.destroy

    render turbo_stream: turbo_stream.remove(dom_id(repeat))
  end

  private

  def repeat_params
    params.require(:repeat).permit(:title, days: [])
  end
end

app/controllers/tasks_controller.rb
class TasksController < AuthenticatedController
  def create
    task = Task.new(task_params)
    task.user = current_user
    task.save

    render turbo_stream: [
      turbo_stream.replace(:task_form, partial: "tasks/form", locals: {task: Task.new}),
      turbo_stream.append(:tasks, partial: "tasks/task", locals: {task: task})
    ]
  end

  def update
    task = current_user.tasks.find(params[:id])
    task.update(status: params[:status], ended_at: Time.zone.now)

    render turbo_stream: turbo_stream.replace(
      dom_id(task),
      partial: "tasks/task",
      locals: {task: task}
    )
  end

  private

  def task_params
    params.require(:task).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/index.html.erb
HOME!

app/views/configurations/show.html.erb
<div class="container max-w-sm mx-auto">
  <h1 class="text-3xl">Configurações</h1>
  <%= form_with(model: @user, url: configurations_path) do |f| %>
    <div class="flex flex-col">
      <%= f.label :timezone %>
      <%= f.time_zone_select :timezone, nil, class: "w-full shadow border rounded mr-2 p-2" %>
      <%= f.submit "Save", class: "mt-2 p-1 text-blue-500 bg-transparent border-2 border-blue-500 rounded hover:text-white hover:bg-blue-500 cursor-pointer" %>
    </div>
  <% end %>
</div>

app/views/events/_event.html.erb
<%= turbo_frame_tag dom_id(event) do %>
  <%= render EventItemComponent.new(event: event) %>
<% end %>

app/views/events/_form.html.erb
<%= form_with(model: event, id: 'event_form') do |f| %>
  <div class="flex">
    <%= render(TextInputComponent.new(name: :title, form: f, placeholder: "Add Event")) %>
    <%= f.datetime_field :datetime, class: "input input-bordered input-primary w-full mr-2" %>
    <%= render(AddButtonComponent.new) %>
  </div>
<% end %>

app/views/home/_backlog.html.erb
<%= turbo_stream_from :in_backlog_tasks %>
<div class="container mx-auto flex flex-col content-center mt-5 lg:mt-10">
  <!-- header -->
  <%= render(SectionTitleComponent.new(title: "Backlog")) %>

  <!-- form -->
  <div class="mb-2">
    <%= render partial: 'tasks/in_backlog_form', locals: { task: backlog_task } %>
  </div>

  <!-- list -->
  <div>
    <%= turbo_frame_tag :in_backlog_tasks do %>
      <%= render backlog_tasks %>
    <% end %>
  </div>
</div>

app/views/home/_events.html.erb
<%= turbo_stream_from :events %>
<div class="container mx-auto flex flex-col content-center mt-5 lg:mt-10">
  <!-- header -->
  <%= render(SectionTitleComponent.new(title: "Events")) %>

  <!-- form -->
  <div class="mb-2">
    <%= render partial: 'events/form', locals: { event: event } %>
  </div>

  <!-- list -->
  <div>
    <%= turbo_frame_tag :events do %>
      <%= render events %>
    <% end %>
  </div>
</div>

app/views/home/_repeats.html.erb
<%= turbo_stream_from :repeats %>
<div class="container mx-auto flex flex-col content-center mt-5 lg:mt-10">
  <!-- header -->
  <%= render(SectionTitleComponent.new(title: "Repeats")) %>

  <!-- form -->
  <div class="mb-2">
    <%= render partial: 'repeats/form', locals: { repeat: repeat } %>
  </div>

  <!-- list -->
  <div>
    <h3 class="text-lg mb-2 text-primary font-bold">Today</h3>
    <%= turbo_frame_tag :repeats do %>
      <%= render today_repeats %>
    <% end %>
    <h3 class="text-lg mb-2 text-primary font-bold mt-5">Other Days</h3>
    <% other_repeats.each do |other_repeat| %>
      <%= render partial: 'repeats/readonly', locals: { repeat: other_repeat } %>
    <% end %>
  </div>
</div>

app/views/home/_tasks.html.erb
<%= turbo_stream_from :tasks %>
<div class="container mx-auto flex flex-col content-center mt-5 lg:mt-10">
  <!-- header -->
  <%= render(SectionTitleComponent.new(title: "Main Tasks")) %>

  <!-- form -->
  <div class="mb-2">
    <%= render partial: 'tasks/form', locals: { task: task } %>
  </div>

  <!-- list -->
  <div>
    <%= turbo_frame_tag :tasks do %>
      <%= render tasks %>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<%= render(NavbarComponent.new) %>
<div class="flex flex-col lg:flex-row px-5">
  <div class="flex-1 mx-1 border-b-4 lg:border-b-0 mb-3 pb-3 border-blue-500	">
    <%= render partial: 'tasks', locals: { task: @task, tasks: @tasks } %>
  </div>
  <div class="flex-1 mx-1 border-b-4 lg:border-b-0 mb-3 pb-3 border-blue-500	">
    <%= render partial: 'repeats', locals: { repeat: @repeat, today_repeats: @today_repeats, other_repeats: @other_repeats } %>
  </div>
  <div class="flex-1 mx-1 border-b-4 lg:border-b-0 mb-3 pb-3 border-blue-500	">
    <%= render partial: 'events', locals: { event: @event, events: @events } %>
  </div>
  <div class="flex-2 text-center mx-1 border-b-4 lg:border-b-0 mb-3 pb-3 border-blue-500	">
    <%= render partial: 'backlog', locals: { backlog_task: @backlog_task, backlog_tasks: @backlog_tasks } %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fordoit</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="icon" type="image/png" sizes="192x192"  href="/favicon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700;900&display=swap" rel="stylesheet">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/login/index.html.erb
<%= button_to 'Login', '/auth/auth0', method: :post, data: { turbo: 'false' } %>

app/views/repeats/_form.html.erb
<%= form_with(model: repeat, id: 'repeat_form') do |f| %>
  <div class="flex">
    <%= render(TextInputComponent.new(name: :title, form: f, placeholder: "Add Repeat")) %>
    <%= render(AddButtonComponent.new) %>
  </div>
  <div class="flex justify-start justify-items-center gap-3 mt-1">
    <%= f.collection_check_boxes :days, {"Sun": 0, "Mon": 1, "Tue": 2, "Wed": 3, "Thu": 4, "Fri": 5, "Sat": 6}, :last, :first do |b| %>
      <div>
        <%= b.check_box %>
        <%= b.label %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/repeats/_readonly.html.erb
<div class="flex flex-col mb-1">
  <div> <%= repeat.title %> </div>
  <div class="flex fle-row gap-x-0.5 mt-1">
    <% ['S', 'M', 'T', 'W', 'T', 'F', 'S'].each_with_index do |day_initial, day_index| %>
      <div class="
        text-xs
        inline-flex
        justify-center
        items-center
        <%= repeat.days.include?(day_index) ? "text-primary-content bg-primary" : "text-neutral-content bg-neutral" %>
        h-4 w-4 rounded-full
      "><%= day_initial %></div>
    <% end %>
  </div>
  <%= %>
</div>

app/views/repeats/_repeat.html.erb
<%= turbo_frame_tag dom_id(repeat) do %>
  <% if repeat.hits.include?(Date.today) %>
    <div class="flex items-center gap-3 my-2">
      <div class="w-full text-left line-through text-blue-500">
        <%= repeat.title %>
      </div>
      <div>
        <%= button_to 'Undo', repeat_path(repeat, hit: :undo), method: :patch, class: "p-1 text-blue-500 bg-transparent border-2 border-blue-500 rounded hover:text-white hover:bg-blue-500 cursor-pointer" %>
      </div>
      <div>
        <%= button_to 'Terminate', repeat_path(repeat), method: :delete, class: "p-1 text-red-500 bg-transparent border-2 border-red-500 rounded hover:text-white hover:bg-red-500 cursor-pointer" %>
      </div>
    </div>
  <% else %>
    <div class="flex w-full gap-x-3">
      <div class="flex-none">
        <%= render(CheckerComponent.new(action: repeat_path(repeat, hit: :done))) %>
      </div>
      <%= render partial: 'repeats/readonly', locals: { repeat: repeat } %>
      <div class="flex-1 text-right">
        <%= button_to 'Terminate', repeat_path(repeat), method: :delete, class: "p-1 text-red-500 bg-transparent border-2 border-red-500 rounded hover:text-white hover:bg-red-500 cursor-pointer" %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/tasks/_cancelled_task.html.erb
<div class="w-full line-through text-red-500">
  <%= task.title %>
  -
  <%= task.status %>
</div>

app/views/tasks/_completed_task.html.erb
<div class="w-full line-through text-blue-500">
  <%= task.title %>
  -
  <%= task.status %>
</div>

app/views/tasks/_form.html.erb
<%= form_with(model: task, id: 'task_form') do |f| %>
  <div class="flex">
    <%= render(TextInputComponent.new(name: :title, form: f, placeholder: "Add Todo")) %>
    <%= render(AddButtonComponent.new) %>
  </div>
<% end %>

app/views/tasks/_in_backlog_form.html.erb
<%= form_with(model: task, url: in_backlog_tasks_path, id: 'in_backlog_task_form') do |f| %>
  <div class="flex">
    <%= render(TextInputComponent.new(name: :title, form: f, placeholder: "Add to Backlog")) %>
    <%= render(AddButtonComponent.new) %>
  </div>
<% end %>

app/views/tasks/_in_backlog_task.html.erb
<div class="w-full text-left">
  <%= task.title %>
</div>
<div>
  <%= button_to 'Move', in_backlog_task_path(task), method: :patch, class: "p-1 text-blue-500 bg-transparent border-2 border-blue-500 rounded hover:text-white hover:bg-blue-500 cursor-pointer" %>
</div>
<div>
  <%= button_to 'Remove', in_backlog_task_path(task), method: :delete, class: "p-1 text-red-500 bg-transparent border-2 border-red-500 rounded hover:text-white hover:bg-red-500 cursor-pointer" %>
</div>

app/views/tasks/_pending_task.html.erb
<div class="flex w-full gap-x-3">
  <div class="flex-none">
    <%= render(CheckerComponent.new(action: task_path(task, status: :completed))) %>
  </div>
  <div>
    <%= task.title %>
  </div>
  <div class="flex-1 text-right">
    <%= button_to 'Cancelled', task_path(task, status: :cancelled), method: :patch, class: "p-1 text-red-500 bg-transparent border-2 border-red-500 rounded hover:text-white hover:bg-red-500 cursor-pointer" %>
  </div>
</div>

app/views/tasks/_task.html.erb
<%= turbo_frame_tag dom_id(task) do %>
  <div class="flex items-center gap-3 my-2">
    <%= render partial: "tasks/#{task.status}_task", locals: { task: task } %>
  </div>
<% end %>

app/views/tasks/index.html.erb
<%= turbo_stream_from :tasks %>
<div class="container mx-auto flex flex-col content-center mt-5 lg:mt-10">
  <!-- header -->
  <h2 class="text-xl text-center mb-2">Main Tasks</h2>

  <!-- form -->
  <div class="mb-2">
    <%= render 'form', task: @task %>
  </div>

  <!-- list -->
  <div>
    <%= turbo_frame_tag :tasks do %>
      <%= render @tasks %>
    <% end %>
  </div>
</div>